name = "The Consortium"
author = "underfr"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcf4ac6084c448143c6d25954843a8c1e5c43de6016da54d425422cca7e70074"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
