name = "The Consortium"
author = "underfr"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "457c59f827b0d5f7809772c8eebfdabaae85882d2828ce3b43c57a4a1cc2ef69"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
