// priority: 20
// The Consortium - the HQ spawn generator (docs/BADGES_AND_HQ.md part 2; PROJECT_RULES 4.1, 4.3, 4.6).
// Loads after consortium_events.js (20, path order) and needs consortium_lib.js (helpers) and, for the arena
// bookkeeping of `hq status` and `hq spawnpoint arena`, the events engine (consortiumArena, consortiumEvents,
// consortiumClaimManager: every call is typeof-guarded). Commands live in the HQ BLOCK of consortium_commands.js.
//
// What it does: /consortium hq build <x> <y> <z> <facing> [<layout>] places the layered layout of
// kubejs/data/consortium/consortium_hq/<layout>.json (generated by tools/hq/build-layout.mjs, checked by
// tools/hq/check-layout.mjs) around an anchor, rotated for one of the four facings, through an in-memory tick
// queue: pass 0 snapshots every position of the box (state plus block entity NBT, run-length encoded) into
// server.persistentData.consortium_hq.record and saves the world before the first write; pass 1 lays the
// foundation and the ground; pass 2 clears the box to air; pass 3 places the layers bottom to top with
// Level.setBlock flags 18 (clients only, known shape, the fastest mode measured) and the block entity NBT in
// the same tick; pass 4 finishes: the shape pass of the `connect` entries (Block.updateFromNeighbourShapes:
// setBlock never computes a placed block's own connections), the `last` entries (the Delivery Terminals after
// their panels: one formation scan), the waystone through the Waystones API, the tagged entities, the survival
// audit (state.canSurvive on every placed position), the force-load release, `built = true`, save-all and the
// report line. /consortium hq clear restores the snapshot (terminals and waystone first, then the bulk) and
// drops the record; hq status, spawnpoint and forget are the bookkeeping. No Consortium Core change: the
// Delivery Station forms from raw placement with no player (verified on the harness).
//
// State (server.persistentData.consortium_hq, its OWN root key: /consortium phase reset removes the
// `consortium` compound and must not touch the HQ bookkeeping): dim, layout, facing, anchor {x,y,z},
// box {x1,y1,z1,x2,y2,z2}, marks.<name> {x,y,z} (world), arena {ringMin, ringMax, pit}, forceloaded, written,
// built, by, special (ListTag of packed offsets: the last and api cells), record { palette (strings), runs
// (ints: packed offset, length | palette index << 8), bes [{p, t}] }. Offsets are measured from the box
// minimum corner: dx | dy << 8 | dz << 16 (the checker's 255 rule is this packing's limit).
//
// Reload safe: the queue is file-level state and dies with a /reload; the force-load ticket does not, so the
// first tick after every script load releases a ticket left by an interrupted build or clear and warns
// (ServerEvents.loaded is not posted by /reload in KubeJS 2101.7.2). No scheduleRepeating.
//
// Rhino note: `const` only at file top level or as the first statements of a function; `let` in blocks.

const CONSORTIUM_HQ_ROOT = 'consortium_hq'
const CONSORTIUM_HQ_TRAPS_ROOT = 'consortium_hq_traps'   // the arena traps of the built layout in world coordinates (consortium_traps.js reads it; hq forget keeps it)
const CONSORTIUM_HQ_TRAP_KINDS = ['pitfall', 'vent', 'arrows']
const CONSORTIUM_HQ_TAG = 'consortium_hq'
const CONSORTIUM_HQ_DATA = 'kubejs/data/consortium/consortium_hq/'
const CONSORTIUM_HQ_FACINGS = ['south', 'west', 'north', 'east'] // clockwise steps from the authored south
const CONSORTIUM_HQ_FOUNDATION = 2              // default fill layers under the floor (-2 and -1); a layout's "foundation" (1..16) overrides it, the deeper layers fill only air, water and soft blocks
const CONSORTIUM_HQ_PER_TICK = 800              // placements per tick (measured: 1000 stone per tick = 14 ms worst, no client)
const CONSORTIUM_HQ_SCAN_PER_TICK = 4000        // examined or snapshotted positions per tick (8,000 read 38 to 48 ms per tick in Rhino on the harness)
const CONSORTIUM_HQ_SLOW_MS = 25                // a step above this halves the next budget
const CONSORTIUM_HQ_BUDGET_FLOOR = 200
const CONSORTIUM_HQ_QUIET_STEPS = 5             // quiet steps before the budget grows back
const CONSORTIUM_HQ_FLAG_BULK = 18              // UPDATE_CLIENTS | UPDATE_KNOWN_SHAPE
const CONSORTIUM_HQ_FLAG_CLIENTS = 2
const CONSORTIUM_HQ_AUDIT_MAX = 20              // offenders printed by the survival audit
const CONSORTIUM_HQ_STAFF_CLAIM_BUFFER = 1      // chunks of buffer around the box in the claim_as advice of hq status (BADGES_AND_HQ 2.8, HQ_SITE 5)

// The staff claim that covers the recorded box: centre (block coordinates), radius in blocks (a chunk multiple
// covering the half-size plus the buffer) and the chunk count of the square claim_as makes of it.
function consortiumHqClaimOf(box) {
  let cx = Math.floor((box.x1 + box.x2) / 2), cz = Math.floor((box.z1 + box.z2) / 2)
  let half = Math.max(box.x2 - box.x1 + 1, box.z2 - box.z1 + 1) / 2
  let chunks = Math.ceil(half / 16) + CONSORTIUM_HQ_STAFF_CLAIM_BUFFER
  return { x: cx, z: cz, radius: chunks * 16, count: (2 * chunks + 1) * (2 * chunks + 1) }
}

const CONSORTIUM_HQ_PARSER = Java.loadClass('net.minecraft.commands.arguments.blocks.BlockStateParser')
const CONSORTIUM_HQ_REGISTRIES = Java.loadClass('net.minecraft.core.registries.Registries')
const CONSORTIUM_HQ_BLOCK = Java.loadClass('net.minecraft.world.level.block.Block')
const CONSORTIUM_HQ_ROTATION = Java.loadClass('net.minecraft.world.level.block.Rotation')
const CONSORTIUM_HQ_AXIS = Java.loadClass('net.minecraft.core.Direction$Axis')
const CONSORTIUM_HQ_CLEARABLE = Java.loadClass('net.minecraft.world.Clearable')
const CONSORTIUM_HQ_TAGPARSER = Java.loadClass('net.minecraft.nbt.TagParser')
const CONSORTIUM_HQ_COMPONENT = Java.loadClass('net.minecraft.network.chat.Component')
const CONSORTIUM_HQ_HAS_WAYSTONES = Platform.isLoaded('waystones')
const CONSORTIUM_HQ_WS_API = CONSORTIUM_HQ_HAS_WAYSTONES ? Java.loadClass('net.blay09.mods.waystones.api.WaystonesAPI') : null
const CONSORTIUM_HQ_WS_STYLES = CONSORTIUM_HQ_HAS_WAYSTONES ? Java.loadClass('net.blay09.mods.waystones.api.WaystoneStyles') : null
const CONSORTIUM_HQ_WS_VIS = CONSORTIUM_HQ_HAS_WAYSTONES ? Java.loadClass('net.blay09.mods.waystones.api.WaystoneVisibility') : null
const CONSORTIUM_HQ_WS_MGR = CONSORTIUM_HQ_HAS_WAYSTONES ? Java.loadClass('net.blay09.mods.waystones.core.WaystoneManagerImpl') : null
const CONSORTIUM_HQ_WS_SYNC = CONSORTIUM_HQ_HAS_WAYSTONES ? Java.loadClass('net.blay09.mods.waystones.core.WaystoneSyncManager') : null

let consortiumHqQueue = null      // the running build or clear, or null
let consortiumHqChecked = false   // the lazy interrupted-run check, once per script load

// ---- JSON access (JsonIO.read gives a Java map; lists are java.util.List) ----------------------------

function consortiumHqGet(o, k) {
  if (o === null || o === undefined) return undefined
  try {
    if (typeof o.get === 'function') {
      let v = o.get(k)
      if (v !== null && v !== undefined) return v
    }
  } catch (err) { /* not a map */ }
  try { return o[k] } catch (err) { return undefined }
}

function consortiumHqKeys(o) {
  let out = []
  if (o === null || o === undefined) return out
  try {
    if (typeof o.keySet === 'function') {
      for (let k of o.keySet()) out.push(String(k))
      return out
    }
  } catch (err) { /* not a map */ }
  for (let k in o) out.push(String(k))
  return out
}

function consortiumHqList(v) {
  let out = []
  if (v === null || v === undefined) return out
  try {
    if (typeof v.size === 'function' && typeof v.get === 'function') {
      for (let i = 0; i < v.size(); i++) out.push(v.get(i))
      return out
    }
  } catch (err) { /* not a list */ }
  if (typeof v.length === 'number') for (let i = 0; i < v.length; i++) out.push(v[i])
  return out
}

function consortiumHqStr(o, k, fallback) {
  let v = consortiumHqGet(o, k)
  return v === null || v === undefined ? (fallback === undefined ? '' : fallback) : String(v)
}

function consortiumHqInt(o, k, fallback) {
  let v = consortiumHqGet(o, k)
  if (v === null || v === undefined) return fallback
  let n = parseInt(String(v), 10)
  return isNaN(n) ? fallback : n
}

function consortiumHqInts(v) {
  let raw = consortiumHqList(v)
  let out = []
  for (let i = 0; i < raw.length; i++) out.push(parseInt(String(raw[i]), 10))
  return out
}

// ---- persistent root ----------------------------------------------------------------------------------

function consortiumHqRoot(server, create) {
  let pd = server.persistentData
  if (!pd.contains(CONSORTIUM_HQ_ROOT)) {
    if (!create) return null
    pd.put(CONSORTIUM_HQ_ROOT, NBT.compoundTag())
  }
  return pd.getCompound(CONSORTIUM_HQ_ROOT)
}

function consortiumHqXyz(tag, x, y, z) {
  tag.putInt('x', x); tag.putInt('y', y); tag.putInt('z', z)
  return tag
}

function consortiumHqBoxOf(root) {
  if (root === null || !root.contains('box')) return null
  let b = root.getCompound('box')
  return { x1: b.getInt('x1'), y1: b.getInt('y1'), z1: b.getInt('z1'), x2: b.getInt('x2'), y2: b.getInt('y2'), z2: b.getInt('z2') }
}

function consortiumHqPack(box, x, y, z) {
  return (x - box.x1) | ((y - box.y1) << 8) | ((z - box.z1) << 16)
}

function consortiumHqUnpack(box, p) {
  return BlockPos.containing(box.x1 + (p & 255), box.y1 + ((p >> 8) & 255), box.z1 + ((p >> 16) & 255))
}

function consortiumHqLevelOf(server, dim) {
  let level = server.getLevel(CONSORTIUM_RL.parse(String(dim)))
  return level === null || level === undefined ? server.overworld() : level
}

// ---- states, rotation, NBT ---------------------------------------------------------------------------

function consortiumHqParseState(level, str) {
  return CONSORTIUM_HQ_PARSER.parseForBlock(level.registryAccess().lookupOrThrow(CONSORTIUM_HQ_REGISTRIES.BLOCK), String(str), false).blockState()
}

function consortiumHqRotationOf(steps) {
  return steps === 1 ? CONSORTIUM_HQ_ROTATION.CLOCKWISE_90 : steps === 2 ? CONSORTIUM_HQ_ROTATION.CLOCKWISE_180 : steps === 3 ? CONSORTIUM_HQ_ROTATION.COUNTERCLOCKWISE_90 : CONSORTIUM_HQ_ROTATION.NONE
}

// Rotates a state by `steps` clockwise quarter turns (BADGES_AND_HQ 2.4): the block's own rotate() first
// (vanilla facing, axis, sign rotation and multipart properties), then, when it returned the same state,
// the generic property walk (a mod block that does not override rotate(): horizontal `facing`, `axis`,
// the north/east/south/west and x/z booleans, the 16-step `rotation`). A `states` map in the palette
// overrides both.
function consortiumHqRotateState(state, steps) {
  if (steps === 0) return state
  let rot = consortiumHqRotationOf(steps)
  let rotated = state.rotate(rot)
  if (rotated !== state) return rotated // === unwraps both sides (Object.equals is not exposed to scripts)
  let out = state
  let props = {}
  for (let prop of state.getProperties()) {
    let name = String(prop.getName())
    props[name] = prop
    let cls = String(prop.getValueClass().getName())
    let v = state.getValue(prop)
    if (cls === 'net.minecraft.core.Direction') {
      if (v.getAxis().isHorizontal()) out = out.setValue(prop, rot.rotate(v))
    } else if (cls === 'net.minecraft.core.Direction$Axis') {
      if (steps % 2 === 1 && !v.isVertical()) out = out.setValue(prop, v === CONSORTIUM_HQ_AXIS.X ? CONSORTIUM_HQ_AXIS.Z : CONSORTIUM_HQ_AXIS.X)
    } else if (name === 'rotation' && cls === 'java.lang.Integer') {
      out = out.setValue(prop, rot.rotate(v, 16))
    }
  }
  let sides = ['north', 'east', 'south', 'west']
  if (props.north && props.east && props.south && props.west) {
    let old = {}
    for (let i = 0; i < 4; i++) old[sides[i]] = state.getValue(props[sides[i]])
    for (let i = 0; i < 4; i++) out = out.setValue(props[sides[(i + steps) % 4]], old[sides[i]])
  }
  if (steps % 2 === 1 && props.x && props.z) {
    let ox = state.getValue(props.x)
    let oz = state.getValue(props.z)
    out = out.setValue(props.x, oz).setValue(props.z, ox)
  }
  return out
}

// The verified front_text NBT of a waxed wall sign (four plain lines, a dye colour).
function consortiumHqSignNbt(lines, color) {
  let msgs = []
  for (let i = 0; i < 4; i++) {
    let text = JSON.stringify({ text: String(lines[i] === undefined || lines[i] === null ? '' : lines[i]) })
    msgs.push("'" + text.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'")
  }
  return '{front_text:{messages:[' + msgs.join(',') + '],color:"' + color + '",has_glowing_text:0b},is_waxed:1b}'
}

function consortiumHqNbt(snbt) {
  return CONSORTIUM_HQ_TAGPARSER.parseTag(String(snbt))
}

// ---- layout loading and compilation -----------------------------------------------------------------

function consortiumHqLoad(name) {
  if (!/^[a-z0-9_]{1,32}$/.test(String(name))) return { ok: false, reason: 'A layout name is [a-z0-9_]{1,32}.' }
  let path = CONSORTIUM_HQ_DATA + name + '.json'
  let raw = null
  try { raw = JsonIO.read(path) } catch (err) { return { ok: false, reason: path + ' is unreadable: ' + err } }
  if (raw === null || raw === undefined) return { ok: false, reason: path + ' is missing.' }
  return { ok: true, raw: raw, path: path }
}

// Local (lx, lz) of a world column, or null outside the rectangle (the apron).
function consortiumHqLocalOf(c, x, z) {
  let rx = x - c.X
  let rz = z - c.Z
  let dx, dz
  if (c.steps === 0) { dx = rx; dz = rz } else if (c.steps === 1) { dx = rz; dz = -rx } else if (c.steps === 2) { dx = -rx; dz = -rz } else { dx = -rz; dz = rx }
  let lx = dx + c.ax
  let lz = dz + c.az
  if (lx < 0 || lx >= c.sizeX || lz < 0 || lz >= c.sizeZ) return null
  return { lx: lx, lz: lz }
}

// World position of a local cell (BADGES_AND_HQ 2.4: (dx, dz) becomes (-dz, dx) per clockwise step).
function consortiumHqWorld(c, lx, ly, lz) {
  let dx = lx - c.ax
  let dz = lz - c.az
  let rx, rz
  if (c.steps === 0) { rx = dx; rz = dz } else if (c.steps === 1) { rx = -dz; rz = dx } else if (c.steps === 2) { rx = -dx; rz = -dz } else { rx = dz; rz = -dx }
  return BlockPos.containing(c.X + rx, c.Y + ly, c.Z + rz)
}

function consortiumHqDirIndex(name) {
  return ['north', 'east', 'south', 'west'].indexOf(String(name))
}

// Parses, validates and rotates a layout for one build: refusal string in `reason`, else the compiled object.
function consortiumHqCompile(level, raw, name, X, Y, Z, facing) {
  let steps = CONSORTIUM_HQ_FACINGS.indexOf(facing)
  if (steps < 0) return { ok: false, reason: 'Facing must be south, west, north or east.' }
  let format = consortiumHqInt(raw, 'format', 0)
  if (format !== 1 && format !== 2) return { ok: false, reason: 'Layout format must be 1 or 2.' }
  // Format 2: cell_width characters per cell (1 or 2) and up to 4096 palette keys; an all-dot or all-space cell is empty.
  let cellWidth = format === 2 && consortiumHqInt(raw, 'cell_width', 1) === 2 ? 2 : 1
  let size = consortiumHqInts(consortiumHqGet(raw, 'size'))
  if (size.length !== 2 || size[0] < 1 || size[0] > 255 || size[1] < 1 || size[1] > 255) return { ok: false, reason: 'size must be [columns 1..255, rows 1..255].' }
  let anchor = consortiumHqInts(consortiumHqGet(raw, 'anchor'))
  if (anchor.length !== 2) return { ok: false, reason: 'anchor must be [x, z].' }
  let c = {
    name: name, X: X, Y: Y, Z: Z, facing: facing, steps: steps, sizeX: size[0], sizeZ: size[1], ax: anchor[0], az: anchor[1],
    apron: Math.max(0, consortiumHqInt(raw, 'apron', 3)), clearTop: consortiumHqInt(raw, 'clear_top', 24),
    palette: {}, cells: [], entities: [], marks: {}, layer0: [], cellWidth: cellWidth, traps: [],
    foundation: Math.max(1, Math.min(16, consortiumHqInt(raw, 'foundation', CONSORTIUM_HQ_FOUNDATION))),
  }
  if (c.clearTop < 1 || c.clearTop > 255) return { ok: false, reason: 'clear_top must be 1..255.' }
  // Every write of a build must lie inside the snapshot box (layers -foundation..clear_top): a cell outside it
  // would be placed but never snapshotted, so hq clear could not restore it (the record's packed offsets cannot
  // even represent it). One message for the three refusals below.
  let boxLayers = 'the snapshot box holds layers -' + c.foundation + '..' + c.clearTop + ' (clear_top): hq clear could never restore it.'
  try {
    c.fill = consortiumHqParseState(level, consortiumHqStr(raw, 'fill', 'minecraft:cobbled_deepslate'))
    c.ground = consortiumHqParseState(level, consortiumHqStr(raw, 'ground', 'minecraft:grass_block'))
    c.air = consortiumHqParseState(level, 'minecraft:air')
  } catch (err) { return { ok: false, reason: 'fill or ground state: ' + err } }
  let arena = consortiumHqGet(raw, 'arena')
  let ring = consortiumHqInts(consortiumHqGet(arena, 'ring'))
  c.arena = { ringMin: ring.length === 2 ? ring[0] : 8, ringMax: ring.length === 2 ? ring[1] : 40, pit: consortiumHqInt(arena, 'pit', 0) }
  // Palette: one parsed and rotated state per key (170 ms for 32k blocks against 771 ms when parsed per block).
  let palette = consortiumHqGet(raw, 'palette')
  let keys = consortiumHqKeys(palette)
  let maxKeys = format === 2 ? 4096 : 92
  if (keys.length === 0 || keys.length > maxKeys) return { ok: false, reason: 'The palette holds ' + keys.length + ' keys (1..' + maxKeys + ').' }
  for (let i = 0; i < keys.length; i++) {
    let k = keys[i]
    if (k.length !== cellWidth || /^[. ]+$/.test(k)) return { ok: false, reason: 'Palette key "' + k + '" is not ' + cellWidth + ' printable character(s).' }
    let def = consortiumHqGet(palette, k)
    let entry = { key: k, connect: false, last: false, api: '', nbt: null, state: null, def: def }
    // A Java String from the map is typeof 'object' in this Rhino: a plain entry is anything that is not a map.
    let isMap = def !== null && def !== undefined && typeof def.get === 'function' && typeof def.keySet === 'function'
    if (!isMap) {
      try { entry.state = consortiumHqRotateState(consortiumHqParseState(level, String(def)), steps) } catch (err) { return { ok: false, reason: 'Palette ' + k + ': ' + err } }
    } else {
      entry.api = consortiumHqStr(def, 'api')
      if (entry.api === 'waystone') {
        entry.style = consortiumHqStr(def, 'style', 'DEFAULT')
        entry.name = consortiumHqStr(def, 'name', 'HQ')
        entry.visibility = consortiumHqStr(def, 'visibility', 'ACTIVATION')
        if (!CONSORTIUM_HQ_HAS_WAYSTONES) return { ok: false, reason: 'Palette ' + k + ' needs the Waystones mod.' }
      } else if (entry.api !== '') {
        return { ok: false, reason: 'Palette ' + k + ': unknown api ' + entry.api + '.' }
      } else {
        entry.connect = String(consortiumHqGet(def, 'connect')) === 'true'
        entry.last = String(consortiumHqGet(def, 'last')) === 'true'
        let states = consortiumHqGet(def, 'states')
        let stateStr = states !== undefined && states !== null && consortiumHqGet(states, facing) !== undefined ? consortiumHqStr(states, facing) : ''
        try {
          entry.state = stateStr ? consortiumHqParseState(level, stateStr) : consortiumHqRotateState(consortiumHqParseState(level, consortiumHqStr(def, 'state')), steps)
        } catch (err) { return { ok: false, reason: 'Palette ' + k + ': ' + err } }
        let sign = consortiumHqGet(def, 'sign')
        let nbt = consortiumHqGet(def, 'nbt')
        try {
          if (sign !== undefined && sign !== null) {
            let lines = consortiumHqList(sign)
            if (lines.length !== 4) return { ok: false, reason: 'Palette ' + k + ': sign must be four lines.' }
            entry.nbt = consortiumHqNbt(consortiumHqSignNbt(lines, consortiumHqStr(def, 'color', 'black')))
          } else if (nbt !== undefined && nbt !== null) {
            let text = String(nbt)
            if (/LootTable/i.test(text)) return { ok: false, reason: 'Palette ' + k + ': a LootTable is refused (rule 4.1).' }
            entry.nbt = consortiumHqNbt(text)
          }
        } catch (err) { return { ok: false, reason: 'Palette ' + k + ' NBT: ' + err } }
      }
    }
    c.palette[k] = entry
  }
  // Layers: rows of size.z strings of size.x characters; '.' and ' ' are empty.
  let layers = consortiumHqList(consortiumHqGet(raw, 'layers'))
  if (layers.length === 0) return { ok: false, reason: 'The layout has no layers.' }
  let byY = {}
  let order = []
  for (let i = 0; i < layers.length; i++) {
    let y = consortiumHqInt(layers[i], 'y', null)
    if (y === null) return { ok: false, reason: 'Layer ' + i + ' has no y.' }
    if (y < -c.foundation || y > c.clearTop) return { ok: false, reason: 'Layer ' + y + ' lies outside the box: ' + boxLayers }
    if (byY[y] !== undefined) return { ok: false, reason: 'Layer ' + y + ' appears twice.' }
    byY[y] = layers[i]
    order.push(y)
  }
  order.sort((a, b) => a - b)
  let rowsOf = (layer, depth) => {
    let same = consortiumHqGet(layer, 'same_as')
    if (same !== undefined && same !== null) {
      let src = byY[parseInt(String(same), 10)]
      if (src === undefined || depth > 4) return null
      return rowsOf(src, depth + 1)
    }
    return consortiumHqList(consortiumHqGet(layer, 'rows'))
  }
  for (let li = 0; li < order.length; li++) {
    let y = order[li]
    let rows = rowsOf(byY[y], 0)
    if (rows === null) return { ok: false, reason: 'Layer ' + y + ': same_as points nowhere.' }
    if (rows.length !== c.sizeZ) return { ok: false, reason: 'Layer ' + y + ' has ' + rows.length + ' rows, expected ' + c.sizeZ + '.' }
    for (let z = 0; z < rows.length; z++) {
      let row = String(rows[z])
      if (row.length !== c.sizeX * cellWidth) return { ok: false, reason: 'Layer ' + y + ' row ' + z + ' has ' + row.length + ' characters, expected ' + (c.sizeX * cellWidth) + '.' }
      if (y === 0) c.layer0.push(row)
      for (let x = 0; x < c.sizeX; x++) {
        let ch = cellWidth === 1 ? row.charAt(x) : row.substring(x * cellWidth, (x + 1) * cellWidth)
        if (ch === '.' || ch === ' ' || ch === '..' || ch === '  ') continue
        if (c.palette[ch] === undefined) return { ok: false, reason: 'Layer ' + y + ' row ' + z + ' column ' + x + ': key "' + ch + '" is not in the palette.' }
        // An api cell (the waystone) owns the cell above it too: both halves must stay inside the box.
        if (c.palette[ch].api !== '' && y + 1 > c.clearTop) return { ok: false, reason: 'Layer ' + y + ' row ' + z + ' column ' + x + ': the ' + c.palette[ch].api + ' cell "' + ch + '" needs its upper half at layer ' + (y + 1) + ', outside the box: ' + boxLayers }
        c.cells.push({ lx: x, ly: y, lz: z, k: ch })
      }
    }
  }
  if (c.layer0.length === 0) for (let z = 0; z < c.sizeZ; z++) c.layer0.push('')
  // Entities and marks.
  let ents = consortiumHqList(consortiumHqGet(raw, 'entities'))
  for (let i = 0; i < ents.length; i++) {
    let at = consortiumHqInts(consortiumHqGet(ents[i], 'at'))
    let dir = consortiumHqDirIndex(consortiumHqStr(ents[i], 'facing'))
    let summon = consortiumHqStr(ents[i], 'summon')
    if (at.length !== 3 || dir < 0 || !/^[a-z0-9_.-]+:[a-z0-9_./-]+$/.test(summon)) return { ok: false, reason: 'Entity ' + i + ' needs at [x,y,z], a horizontal facing and a summon id.' }
    // Inside the rectangle (the checker's rule) and inside the box layers: hq clear kills the tagged entities of the box only.
    if (at[0] < 0 || at[0] >= c.sizeX || at[2] < 0 || at[2] >= c.sizeZ) return { ok: false, reason: 'Entity ' + i + ' at ' + at.join(' ') + ' lies outside the layout rectangle (x 0..' + (c.sizeX - 1) + ', z 0..' + (c.sizeZ - 1) + ').' }
    if (at[1] < -c.foundation || at[1] > c.clearTop) return { ok: false, reason: 'Entity ' + i + ' at ' + at.join(' ') + ' lies outside the box: ' + boxLayers }
    let nbt = consortiumHqStr(ents[i], 'nbt', '')
    if (/LootTable/i.test(nbt)) return { ok: false, reason: 'Entity ' + i + ': a LootTable is refused (rule 4.1).' }
    c.entities.push({ lx: at[0], ly: at[1], lz: at[2], dir: dir, summon: summon, nbt: nbt })
  }
  // Traps (layout format 2): { kind, cells [[x,y,z]], trigger [[x,y,z]] }, every cell inside the box.
  let trapsRaw = consortiumHqList(consortiumHqGet(raw, 'traps'))
  for (let i = 0; i < trapsRaw.length; i++) {
    let kind = consortiumHqStr(trapsRaw[i], 'kind', '')
    if (CONSORTIUM_HQ_TRAP_KINDS.indexOf(kind) < 0) return { ok: false, reason: 'Trap ' + i + ': unknown kind "' + kind + '" (pitfall, vent or arrows).' }
    let group = { kind: kind, cells: [], trigger: [] }
    for (let part of ['cells', 'trigger']) {
      let list = consortiumHqList(consortiumHqGet(trapsRaw[i], part))
      for (let j = 0; j < list.length; j++) {
        let xyz = consortiumHqInts(list[j])
        if (xyz.length !== 3) return { ok: false, reason: 'Trap ' + i + ' ' + part + ' ' + j + ' must be [x, y, z].' }
        if (xyz[0] < 0 || xyz[0] >= c.sizeX || xyz[2] < 0 || xyz[2] >= c.sizeZ || xyz[1] < -c.foundation || xyz[1] > c.clearTop) return { ok: false, reason: 'Trap ' + i + ' ' + part + ' ' + j + ' at ' + xyz.join(' ') + ' lies outside the layout box.' }
        group[part].push(xyz)
      }
    }
    if (group.cells.length === 0) return { ok: false, reason: 'Trap ' + i + ' has no cells.' }
    c.traps.push(group)
  }
  let marks = consortiumHqGet(raw, 'marks')
  let markNames = consortiumHqKeys(marks)
  for (let i = 0; i < markNames.length; i++) {
    let m = consortiumHqInts(consortiumHqGet(marks, markNames[i]))
    if (m.length !== 3) return { ok: false, reason: 'Mark ' + markNames[i] + ' must be [x, y, z].' }
    c.marks[markNames[i]] = m
  }
  for (let i = 0; i < ['spawn', 'arena', 'terminal'].length; i++) {
    if (c.marks[['spawn', 'arena', 'terminal'][i]] === undefined) return { ok: false, reason: 'Mark ' + ['spawn', 'arena', 'terminal'][i] + ' is mandatory.' }
  }
  // The world box: the rectangle plus the apron, layers -foundation..clear_top, rotated.
  let corners = [[-c.apron, -c.apron], [c.sizeX - 1 + c.apron, -c.apron], [-c.apron, c.sizeZ - 1 + c.apron], [c.sizeX - 1 + c.apron, c.sizeZ - 1 + c.apron]]
  let box = { x1: 1e9, z1: 1e9, x2: -1e9, z2: -1e9, y1: Y - c.foundation, y2: Y + c.clearTop }
  for (let i = 0; i < corners.length; i++) {
    let p = consortiumHqWorld(c, corners[i][0], 0, corners[i][1])
    box.x1 = Math.min(box.x1, p.getX()); box.x2 = Math.max(box.x2, p.getX())
    box.z1 = Math.min(box.z1, p.getZ()); box.z2 = Math.max(box.z2, p.getZ())
  }
  c.box = box
  // 254 on x: a run is packed as length | index << 8 and a run may span a whole row (width 255 would overflow)
  if (box.x2 - box.x1 >= 255 || box.z2 - box.z1 > 255 || box.y2 - box.y1 > 255) return { ok: false, reason: 'The box exceeds 254 blocks on x or 255 blocks on y or z.' }
  return { ok: true, c: c }
}

// ---- chunk forcing -----------------------------------------------------------------------------------

function consortiumHqForce(level, box, on) {
  let n = 0
  for (let cx = box.x1 >> 4; cx <= box.x2 >> 4; cx++) {
    for (let cz = box.z1 >> 4; cz <= box.z2 >> 4; cz++) {
      level.setChunkForced(cx, cz, on)
      n++
    }
  }
  return n
}

// ---- messages ------------------------------------------------------------------------------------------

function consortiumHqLog(text) {
  console.info('[Consortium] HQ: ' + text)
}

// Tells the ops online and the player who ran the command (yellow), and logs.
function consortiumHqNotify(server, by, text, red) {
  consortiumHqLog(text)
  for (let p of server.players) {
    if (p.hasPermissions(2) || String(p.username) === String(by)) p.tell(red ? Text.of('[HQ] ' + text).red() : Text.of('[HQ] ' + text).yellow())
  }
}

// 'snapshot 87, ground 12, ...' for the finish line.
function consortiumHqWorstText(q) {
  let parts = []
  for (let k in q.phaseWorst) parts.push(k + ' ' + q.phaseWorst[k])
  return parts.join(', ')
}

function consortiumHqPosText(p) {
  return p.getX() + ' ' + p.getY() + ' ' + p.getZ()
}

// ---- the build ------------------------------------------------------------------------------------------

function consortiumHqBusyText() {
  if (consortiumHqQueue === null) return ''
  let q = consortiumHqQueue
  return q.kind + ' in progress (phase ' + q.phase + ', ' + q.done + ' of ' + q.todo + ')'
}

// /consortium hq build. Returns { ok, text } or { ok: false, reason }.
function consortiumHqBuild(server, level, X, Y, Z, facing, layoutName, by) {
  if (consortiumHqQueue !== null) return { ok: false, reason: 'An HQ ' + consortiumHqBusyText() + ' runs: wait for its finish line.' }
  let root = consortiumHqRoot(server, false)
  if (root !== null && root.contains('box')) return { ok: false, reason: 'An HQ box is recorded (' + root.getString('layout') + ' at ' + root.getCompound('anchor').getInt('x') + ' ' + root.getCompound('anchor').getInt('y') + ' ' + root.getCompound('anchor').getInt('z') + ' facing ' + root.getString('facing') + '): run consortium hq clear first (or hq forget to keep the blocks).' }
  let loaded = consortiumHqLoad(layoutName)
  if (!loaded.ok) return loaded
  let compiled = consortiumHqCompile(level, loaded.raw, String(layoutName), X, Y, Z, facing)
  if (!compiled.ok) return compiled
  let c = compiled.c
  let box = c.box
  root = consortiumHqRoot(server, true)
  root.putString('dim', String(level.dimension))
  root.putString('layout', c.name)
  root.putString('facing', facing)
  root.putString('by', String(by))
  root.put('anchor', consortiumHqXyz(NBT.compoundTag(), X, Y, Z))
  let b = NBT.compoundTag()
  b.putInt('x1', box.x1); b.putInt('y1', box.y1); b.putInt('z1', box.z1); b.putInt('x2', box.x2); b.putInt('y2', box.y2); b.putInt('z2', box.z2)
  root.put('box', b)
  let marks = NBT.compoundTag()
  for (let name in c.marks) {
    let p = consortiumHqWorld(c, c.marks[name][0], c.marks[name][1], c.marks[name][2])
    marks.put(name, consortiumHqXyz(NBT.compoundTag(), p.getX(), p.getY(), p.getZ()))
  }
  root.put('marks', marks)
  let arena = NBT.compoundTag()
  arena.putInt('ringMin', c.arena.ringMin); arena.putInt('ringMax', c.arena.ringMax); arena.putInt('pit', c.arena.pit)
  root.put('arena', arena)
  let special = NBT.listTag()
  for (let i = 0; i < c.cells.length; i++) {
    let e = c.palette[c.cells[i].k]
    if (!e.last && e.api === '') continue
    let p = consortiumHqWorld(c, c.cells[i].lx, c.cells[i].ly, c.cells[i].lz)
    special.add(NBT.intTag(consortiumHqPack(box, p.getX(), p.getY(), p.getZ())))
    if (e.api === 'waystone') special.add(NBT.intTag(consortiumHqPack(box, p.getX(), p.getY() + 1, p.getZ())))
  }
  root.put('special', special)
  // The traps root: world coordinates for consortium_traps.js; the mode survives a rebuild (off, on or events).
  let pd = server.persistentData
  let oldMode = pd.contains(CONSORTIUM_HQ_TRAPS_ROOT) ? String(pd.getCompound(CONSORTIUM_HQ_TRAPS_ROOT).getString('mode')) : ''
  let trapsRoot = NBT.compoundTag()
  trapsRoot.putString('dim', String(level.dimension))
  trapsRoot.putString('layout', c.name)
  trapsRoot.putString('mode', oldMode || 'events')
  let am = consortiumHqWorld(c, c.marks.arena[0], c.marks.arena[1], c.marks.arena[2])
  trapsRoot.put('arena', consortiumHqXyz(NBT.compoundTag(), am.getX(), am.getY(), am.getZ()))
  let trapList = NBT.listTag()
  for (let i = 0; i < c.traps.length; i++) {
    let t = NBT.compoundTag()
    t.putString('kind', c.traps[i].kind)
    for (let part of ['cells', 'trigger']) {
      let flat = NBT.listTag()
      for (let j = 0; j < c.traps[i][part].length; j++) {
        let w = consortiumHqWorld(c, c.traps[i][part][j][0], c.traps[i][part][j][1], c.traps[i][part][j][2])
        flat.add(NBT.intTag(w.getX())); flat.add(NBT.intTag(w.getY())); flat.add(NBT.intTag(w.getZ()))
      }
      t.put(part, flat)
    }
    trapList.add(t)
  }
  trapsRoot.put('traps', trapList)
  pd.put(CONSORTIUM_HQ_TRAPS_ROOT, trapsRoot)
  root.putBoolean('forceloaded', true)
  root.putBoolean('written', false)
  root.putBoolean('built', false)
  root.remove('record')
  let chunks = consortiumHqForce(level, box, true)
  let width = box.x2 - box.x1 + 1
  let depth = box.z2 - box.z1 + 1
  let height = box.y2 - box.y1 + 1
  consortiumHqQueue = {
    kind: 'build', server: server, level: level, c: c, box: box, by: String(by), startedAt: Date.now(), startTick: server.tickCount,
    phase: 'snapshot', i: 0, todo: width * depth * height, done: 0, placements: 0, outside: 0, worst: 0, phaseWorst: {}, ticks: 0, snapshotTicks: 0,
    budget: CONSORTIUM_HQ_PER_TICK, scanBudget: CONSORTIUM_HQ_SCAN_PER_TICK, quiet: 0,
    width: width, depth: depth, height: height,
    rec: { palette: [], index: {}, runs: [], bes: [], runStart: -1, runLen: 0, runIdx: -1, runState: null },
    columns: null, audit: [],
  }
  consortiumHqLog(by + ' hq build ' + X + ' ' + Y + ' ' + Z + ' ' + facing + ' ' + c.name + ': box ' + box.x1 + ' ' + box.y1 + ' ' + box.z1 + ' to ' + box.x2 + ' ' + box.y2 + ' ' + box.z2 + ' (' + chunks + ' chunks force-loaded), ' + c.cells.length + ' layout cells, snapshot of ' + consortiumHqQueue.todo + ' positions first')
  return { ok: true, text: 'HQ build started: box ' + box.x1 + ' ' + box.y1 + ' ' + box.z1 + ' to ' + box.x2 + ' ' + box.y2 + ' ' + box.z2 + ' (' + width + ' x ' + height + ' x ' + depth + ', ' + chunks + ' chunks), ' + c.cells.length + ' layout cells plus the ground; the snapshot of ' + consortiumHqQueue.todo + ' positions runs first, the finish line follows.' }
}

// The snapshot pass: run-length encodes the pre-build state of every position of the box.
function consortiumHqSnapshotStep(q) {
  let level = q.level
  let box = q.box
  let rec = q.rec
  let ra = level.registryAccess()
  let end = Math.min(q.todo, q.i + q.scanBudget)
  for (; q.i < end; q.i++) {
    let dx = q.i % q.width
    let dz = Math.floor(q.i / q.width) % q.depth
    let dy = Math.floor(q.i / (q.width * q.depth))
    let pos = BlockPos.containing(box.x1 + dx, box.y1 + dy, box.z1 + dz)
    let state = level.getBlockState(pos)
    let packed = dx | (dy << 8) | (dz << 16)
    if (rec.runState !== null && dx !== 0 && state === rec.runState) {
      rec.runLen++
    } else {
      if (rec.runState !== null) { rec.runs.push(rec.runStart); rec.runs.push(rec.runLen | (rec.runIdx << 8)) }
      let str = String(CONSORTIUM_HQ_PARSER.serialize(state))
      let idx = rec.index[str]
      if (idx === undefined) { idx = rec.palette.length; rec.palette.push(str); rec.index[str] = idx }
      rec.runStart = packed; rec.runLen = 1; rec.runIdx = idx; rec.runState = state
    }
    if (state.hasBlockEntity()) {
      let be = level.getBlockEntity(pos)
      if (be !== null) rec.bes.push({ p: packed, t: be.saveWithoutMetadata(ra) })
    }
  }
  q.done = q.i
  if (q.i < q.todo) return false
  if (rec.runState !== null) { rec.runs.push(rec.runStart); rec.runs.push(rec.runLen | (rec.runIdx << 8)) }
  // Persist the record and save before the first world write.
  let tag = NBT.compoundTag()
  let palette = NBT.listTag()
  for (let i = 0; i < rec.palette.length; i++) palette.add(NBT.stringTag(rec.palette[i]))
  tag.put('palette', palette)
  let runs = NBT.listTag()
  for (let i = 0; i < rec.runs.length; i++) runs.add(NBT.intTag(rec.runs[i]))
  tag.put('runs', runs)
  let bes = NBT.listTag()
  for (let i = 0; i < rec.bes.length; i++) {
    let e = NBT.compoundTag()
    e.putInt('p', rec.bes[i].p)
    e.put('t', rec.bes[i].t)
    bes.add(e)
  }
  tag.put('bes', bes)
  let root = consortiumHqRoot(q.server, true)
  root.put('record', tag)
  root.putBoolean('written', true)
  q.server.runCommandSilent('save-all')
  consortiumHqLog('snapshot done: ' + q.todo + ' positions, ' + (rec.runs.length / 2) + ' runs, ' + rec.palette.length + ' states, ' + rec.bes.length + ' block entities, ' + q.snapshotTicks + ' ticks; the world is saved, the ground pass starts')
  q.rec = null
  return true
}

// Columns of the box in world coordinates with their local cell (null in the apron).
function consortiumHqColumns(q) {
  let out = []
  for (let z = q.box.z1; z <= q.box.z2; z++) {
    for (let x = q.box.x1; x <= q.box.x2; x++) out.push({ x: x, z: z, local: consortiumHqLocalOf(q.c, x, z) })
  }
  return out
}

// Every bulk write of a build (and of the wipe fallback) goes through here. A position outside the snapshot
// box could never be restored by hq clear, so it is skipped, warned once on the console and counted for the
// finish line (BADGES_AND_HQ 2.4). The compile refusals make this unreachable for a layout that passed: it
// is the safety net for the next layout bug.
function consortiumHqPlace(q, pos, state, flags) {
  let box = q.box
  let x = pos.getX(), y = pos.getY(), z = pos.getZ()
  if (x < box.x1 || x > box.x2 || y < box.y1 || y > box.y2 || z < box.z1 || z > box.z2) {
    q.outside++
    if (q.outside === 1) console.warn('[Consortium] HQ ' + q.kind + ': a write at ' + x + ' ' + y + ' ' + z + ' falls outside the box ' + box.x1 + ' ' + box.y1 + ' ' + box.z1 + ' to ' + box.x2 + ' ' + box.y2 + ' ' + box.z2 + ' and is skipped (a layout bug: the snapshot could not restore it)')
    return
  }
  let old = q.level.getBlockState(pos)
  if (old.hasBlockEntity() && old !== state) {
    // what /fill and /setblock do: a chest or barrel inside the box must not spill its items as entities
    let be = q.level.getBlockEntity(pos)
    if (be !== null) CONSORTIUM_HQ_CLEARABLE.tryClear(be)
  }
  q.level.setBlock(pos, state, flags)
  q.placements++
}

// ', 3 write(s) outside the box skipped' for the finish lines, or ''.
function consortiumHqOutsideText(q) {
  return q.outside > 0 ? ', ' + q.outside + ' write(s) outside the box skipped (see the console)' : ''
}

// The ground pass: the fill layers under every column and the ground where the layer 0 map is empty.
function consortiumHqGroundStep(q) {
  let level = q.level
  let c = q.c
  if (q.columns === null) { q.columns = consortiumHqColumns(q); q.todo = q.columns.length; q.i = 0 }
  let end = Math.min(q.todo, q.i + Math.floor(q.scanBudget / 24)) // three reads and up to three writes per column into terrain or water: the light engine makes this the slowest write (50 ms per 333 columns measured)
  for (; q.i < end; q.i++) {
    let col = q.columns[q.i]
    for (let f = 1; f <= c.foundation; f++) {
      let pos = BlockPos.containing(col.x, c.Y - f, col.z)
      let st = level.getBlockState(pos)
      if (st === c.fill) continue
      // the two layers under the floor are always the fill; deeper layers only replace air, fluids and soft blocks
      if (f > CONSORTIUM_HQ_FOUNDATION && !st.isAir() && st.isSolid() && st.getFluidState().isEmpty()) continue
      consortiumHqPlace(q, pos, c.fill, CONSORTIUM_HQ_FLAG_BULK)
    }
    let empty = col.local === null
    if (!empty) {
      let row = c.layer0[col.local.lz]
      let w = c.cellWidth
      let ch = (col.local.lx + 1) * w <= row.length ? row.substring(col.local.lx * w, (col.local.lx + 1) * w) : '.'
      empty = ch === '.' || ch === ' ' || ch === '..' || ch === '  '
    }
    if (empty) {
      let pos = BlockPos.containing(col.x, c.Y, col.z)
      if (level.getBlockState(pos) !== c.ground) consortiumHqPlace(q, pos, c.ground, CONSORTIUM_HQ_FLAG_BULK)
    }
  }
  q.done = q.i
  return q.i >= q.todo
}

// The clear pass: layers 1..clear_top of every column to air where not air.
function consortiumHqClearStep(q) {
  let level = q.level
  let c = q.c
  if (q.columns === null) { q.columns = consortiumHqColumns(q); q.i = 0 }
  let height = c.clearTop
  if (q.todo !== q.columns.length * height) { q.todo = q.columns.length * height; q.i = 0 }
  let end = Math.min(q.todo, q.i + q.scanBudget)
  for (; q.i < end; q.i++) {
    let col = q.columns[q.i % q.columns.length]
    let layer = 1 + Math.floor(q.i / q.columns.length)
    let pos = BlockPos.containing(col.x, c.Y + layer, col.z)
    if (!level.getBlockState(pos).isAir()) consortiumHqPlace(q, pos, c.air, CONSORTIUM_HQ_FLAG_BULK)
  }
  q.done = q.i
  return q.i >= q.todo
}

// The layer pass: every non-empty cell bottom to top (last and api entries wait for the finish pass).
function consortiumHqLayersStep(q) {
  let level = q.level
  let c = q.c
  let ra = level.registryAccess()
  if (q.todo !== c.cells.length) { q.todo = c.cells.length; q.i = 0 }
  let end = Math.min(q.todo, q.i + q.budget)
  for (; q.i < end; q.i++) {
    let cell = c.cells[q.i]
    let e = c.palette[cell.k]
    if (e.last || e.api !== '') continue
    let pos = consortiumHqWorld(c, cell.lx, cell.ly, cell.lz)
    consortiumHqPlace(q, pos, e.state, CONSORTIUM_HQ_FLAG_BULK)
    if (e.nbt !== null) {
      let be = level.getBlockEntity(pos)
      if (be !== null) be.loadWithComponents(e.nbt, ra)
    }
  }
  q.done = q.i
  return q.i >= q.todo
}

// The finish pass, one sub-step per tick: connect, last, api, entities, audit, release.
function consortiumHqFinishStep(q) {
  let level = q.level
  let c = q.c
  let server = q.server
  let ra = level.registryAccess()
  if (q.sub === undefined) { q.sub = 'connect'; q.i = 0; q.todo = c.cells.length; q.fixed = 0 }
  if (q.sub === 'connect') {
    let end = Math.min(q.todo, q.i + q.scanBudget)
    for (; q.i < end; q.i++) {
      let cell = c.cells[q.i]
      let e = c.palette[cell.k]
      if (!e.connect) continue
      let pos = consortiumHqWorld(c, cell.lx, cell.ly, cell.lz)
      let old = level.getBlockState(pos)
      let fixed = CONSORTIUM_HQ_BLOCK.updateFromNeighbourShapes(old, level, pos)
      if (fixed !== old) { level.setBlock(pos, fixed, CONSORTIUM_HQ_FLAG_CLIENTS); q.fixed++ }
    }
    q.done = q.i
    if (q.i < q.todo) return false
    q.sub = 'last'; q.i = 0
    return false
  }
  if (q.sub === 'last') {
    for (let i = 0; i < c.cells.length; i++) {
      let cell = c.cells[i]
      let e = c.palette[cell.k]
      if (!e.last) continue
      let pos = consortiumHqWorld(c, cell.lx, cell.ly, cell.lz)
      consortiumHqPlace(q, pos, e.state, CONSORTIUM_HQ_FLAG_CLIENTS)
      if (e.nbt !== null) {
        let be = level.getBlockEntity(pos)
        if (be !== null) be.loadWithComponents(e.nbt, ra)
      }
    }
    q.sub = 'api'
    return false
  }
  if (q.sub === 'api') {
    for (let i = 0; i < c.cells.length; i++) {
      let cell = c.cells[i]
      let e = c.palette[cell.k]
      if (e.api !== 'waystone') continue
      let pos = consortiumHqWorld(c, cell.lx, cell.ly, cell.lz)
      try {
        let opt = CONSORTIUM_HQ_WS_API.placeWaystone(level, pos, CONSORTIUM_HQ_WS_STYLES[e.style])
        if (opt.isPresent()) {
          let ws = opt.get()
          ws.setName(CONSORTIUM_HQ_COMPONENT.literal(e.name))
          ws.setVisibility(CONSORTIUM_HQ_WS_VIS[e.visibility])
          CONSORTIUM_HQ_WS_MGR.get(server).updateWaystone(ws)
          CONSORTIUM_HQ_WS_SYNC.sendWaystoneUpdateToAll(server, ws)
          q.placements += 2
          consortiumHqLog('waystone "' + e.name + '" (' + e.visibility + ') placed at ' + consortiumHqPosText(pos))
        } else {
          q.audit.push('waystone at ' + consortiumHqPosText(pos) + ' was not placed (API answered empty)')
        }
      } catch (err) { q.audit.push('waystone at ' + consortiumHqPosText(pos) + ' failed: ' + err) }
    }
    q.sub = 'entities'
    return false
  }
  if (q.sub === 'entities') {
    let dim = String(level.dimension)
    for (let i = 0; i < c.entities.length; i++) {
      let en = c.entities[i]
      let pos = consortiumHqWorld(c, en.lx, en.ly, en.lz)
      let dir = (en.dir + c.steps) % 4 // north, east, south, west clockwise
      let facingByte = [2, 5, 3, 4][dir]
      let inner = en.nbt.trim().replace(/^\{/, '').replace(/\}$/, '').trim()
      let nbt = '{Tags:["' + CONSORTIUM_HQ_TAG + '"],Facing:' + facingByte + 'b' + (inner ? ',' + inner : '') + '}'
      server.runCommandSilent('execute in ' + dim + ' run summon ' + en.summon + ' ' + consortiumHqPosText(pos) + ' ' + nbt)
      q.placements++
    }
    q.sub = 'audit'; q.i = 0; q.todo = c.cells.length
    return false
  }
  if (q.sub === 'audit') {
    let end = Math.min(q.todo, q.i + Math.floor(q.scanBudget / 2)) // canSurvive plus a state read per cell
    for (; q.i < end; q.i++) {
      let cell = c.cells[q.i]
      let e = c.palette[cell.k]
      if (e.api !== '') continue
      let pos = consortiumHqWorld(c, cell.lx, cell.ly, cell.lz)
      let st = level.getBlockState(pos)
      if (st.getBlock() !== e.state.getBlock()) q.audit.push('key ' + cell.k + ' at ' + consortiumHqPosText(pos) + ' reads ' + String(CONSORTIUM_HQ_PARSER.serialize(st)) + ' instead of ' + String(CONSORTIUM_HQ_PARSER.serialize(e.state)))
      else if (!st.canSurvive(level, pos)) q.audit.push('key ' + cell.k + ' (' + String(CONSORTIUM_HQ_PARSER.serialize(st)) + ') at ' + consortiumHqPosText(pos) + ' cannot survive there')
    }
    q.done = q.i
    if (q.i < q.todo) return false
    q.sub = 'release'
    return false
  }
  // release
  consortiumHqForce(level, q.box, false)
  let root = consortiumHqRoot(server, true)
  root.putBoolean('forceloaded', false)
  root.putBoolean('built', true)
  server.runCommandSilent('save-all')
  let ticks = server.tickCount - q.startTick
  let audit = q.audit.length === 0 ? 'survival audit clean' : 'survival audit: ' + q.audit.length + ' offender(s)'
  consortiumHqNotify(server, q.by, 'built: ' + consortiumFmt(q.placements) + ' placements in ' + ticks + ' ticks (' + q.snapshotTicks + ' snapshot), worst tick ' + q.worst + ' ms (' + consortiumHqWorstText(q) + '), ' + q.fixed + ' shapes fixed, ' + audit + consortiumHqOutsideText(q) + '. Next: consortium hq status.', q.audit.length > 0 || q.outside > 0)
  for (let i = 0; i < Math.min(CONSORTIUM_HQ_AUDIT_MAX, q.audit.length); i++) consortiumHqLog('  audit: ' + q.audit[i])
  if (q.audit.length > CONSORTIUM_HQ_AUDIT_MAX) consortiumHqLog('  audit: ' + (q.audit.length - CONSORTIUM_HQ_AUDIT_MAX) + ' more')
  return true
}

// ---- the clear ---------------------------------------------------------------------------------------------

// /consortium hq clear. Returns { ok, text } or { ok: false, reason }.
function consortiumHqClear(server, by) {
  if (consortiumHqQueue !== null) return { ok: false, reason: 'An HQ ' + consortiumHqBusyText() + ' runs: wait for its finish line.' }
  let root = consortiumHqRoot(server, false)
  let box = consortiumHqBoxOf(root)
  if (box === null) return { ok: false, reason: 'No HQ box is recorded: nothing to clear.' }
  let level = consortiumHqLevelOf(server, root.getString('dim'))
  if (!root.getBoolean('written')) {
    // The build never left the snapshot pass: nothing was written, the box is simply dropped.
    consortiumHqForce(level, box, false)
    server.persistentData.remove(CONSORTIUM_HQ_ROOT)
    consortiumHqLog(by + ' hq clear: nothing was written, the box is dropped')
    return { ok: true, text: 'Nothing was written by that build (it never left the snapshot pass): the box is dropped.' }
  }
  let q = {
    kind: 'clear', server: server, level: level, box: box, by: String(by), startedAt: Date.now(), startTick: server.tickCount,
    phase: 'kill', i: 0, todo: 1, done: 0, placements: 0, outside: 0, worst: 0, phaseWorst: {}, ticks: 0, snapshotTicks: 0,
    budget: CONSORTIUM_HQ_PER_TICK, scanBudget: CONSORTIUM_HQ_SCAN_PER_TICK, quiet: 0, audit: [],
    palette: [], runs: null, beMap: {}, special: [], wipe: false, c: null,
  }
  try {
    if (!root.contains('record')) throw new Error('no record')
    let rec = root.getCompound('record')
    let palette = rec.getList('palette', 8) // 8 = string tags
    for (let i = 0; i < palette.size(); i++) q.palette.push(consortiumHqParseState(level, String(palette.getString(i))))
    let runs = rec.getList('runs', 3) // 3 = int tags
    q.runs = runs
    q.todo = runs.size() / 2
    let bes = rec.getList('bes', 10) // 10 = compounds
    for (let i = 0; i < bes.size(); i++) {
      let e = bes.getCompound(i)
      q.beMap[e.getInt('p')] = e.getCompound('t')
    }
    let special = root.getList('special', 3)
    for (let i = 0; i < special.size(); i++) q.special.push(special.getInt(i))
  } catch (err) {
    // A record that fails to parse: the wipe fallback (air above the floor, ground at the floor, fill below).
    q.wipe = true
    let anchor = root.getCompound('anchor')
    let loaded = consortiumHqLoad(String(root.getString('layout')))
    let compiled = loaded.ok ? consortiumHqCompile(level, loaded.raw, String(root.getString('layout')), anchor.getInt('x'), anchor.getInt('y'), anchor.getInt('z'), String(root.getString('facing'))) : { ok: false }
    if (compiled.ok) q.c = compiled.c
    else q.c = { X: anchor.getInt('x'), Y: anchor.getInt('y'), Z: anchor.getInt('z'), steps: 0, ax: 0, az: 0, sizeX: 0, sizeZ: 0, clearTop: box.y2 - anchor.getInt('y'), fill: consortiumHqParseState(level, 'minecraft:cobbled_deepslate'), ground: consortiumHqParseState(level, 'minecraft:grass_block'), layer0: [] }
    consortiumHqNotify(server, by, 'the snapshot record cannot be read (' + err + '): falling back to a wipe of the box (air above the floor, ground at the floor level, fill below)', true)
  }
  root.putBoolean('forceloaded', true)
  consortiumHqForce(level, box, true)
  consortiumHqQueue = q
  consortiumHqLog(by + ' hq clear: box ' + box.x1 + ' ' + box.y1 + ' ' + box.z1 + ' to ' + box.x2 + ' ' + box.y2 + ' ' + box.z2 + (q.wipe ? ' (wipe fallback)' : ', ' + q.todo + ' runs to restore'))
  return { ok: true, text: 'HQ clear started' + (q.wipe ? ' (wipe fallback, the record was unreadable)' : ': ' + q.todo + ' runs to restore') + '; the tagged entities go first, then the terminals and the waystone, then the bulk.' }
}

function consortiumHqRestoreAt(q, pos, packed, state) {
  let level = q.level
  if (level.getBlockState(pos) !== state) { level.setBlock(pos, state, CONSORTIUM_HQ_FLAG_CLIENTS); q.placements++ }
  let nbt = q.beMap[packed]
  if (nbt !== undefined) {
    let be = level.getBlockEntity(pos)
    if (be !== null) be.loadWithComponents(nbt, level.registryAccess())
  }
}

// The recorded state of one packed position (a linear search over the runs: the preface has a few cells).
function consortiumHqRecordedState(q, packed) {
  let dx = packed & 255, dy = (packed >> 8) & 255, dz = (packed >> 16) & 255
  for (let i = 0; i < q.runs.size(); i += 2) {
    let start = q.runs.getInt(i)
    let v = q.runs.getInt(i + 1)
    let len = v & 255
    if (((start >> 8) & 255) !== dy || ((start >> 16) & 255) !== dz) continue
    let sx = start & 255
    if (dx >= sx && dx < sx + len) return q.palette[v >> 8]
  }
  return null
}

function consortiumHqClearStepRun(q) {
  let server = q.server
  let level = q.level
  let box = q.box
  if (q.phase === 'kill') {
    server.runCommandSilent('execute in ' + String(level.dimension) + ' run kill @e[tag=' + CONSORTIUM_HQ_TAG + ',x=' + box.x1 + ',y=' + box.y1 + ',z=' + box.z1 + ',dx=' + (box.x2 - box.x1) + ',dy=' + (box.y2 - box.y1) + ',dz=' + (box.z2 - box.z1) + ']')
    q.phase = q.wipe ? 'wipe' : 'preface'
    q.i = 0
    return false
  }
  if (q.phase === 'preface') {
    // The terminals (their removal releases the panels in one scan) and the waystone halves, in one tick.
    for (let i = 0; i < q.special.length; i++) {
      let state = consortiumHqRecordedState(q, q.special[i])
      if (state !== null) consortiumHqRestoreAt(q, consortiumHqUnpack(box, q.special[i]), q.special[i], state)
    }
    q.phase = 'restore'
    q.i = 0
    q.done = 0
    return false
  }
  if (q.phase === 'restore') {
    let count = 0
    while (q.i < q.todo && count < q.budget) {
      let start = q.runs.getInt(q.i * 2)
      let v = q.runs.getInt(q.i * 2 + 1)
      let len = v & 255
      let state = q.palette[v >> 8]
      for (let k = 0; k < len; k++) consortiumHqRestoreAt(q, consortiumHqUnpack(box, start + k), start + k, state)
      count += len
      q.i++
    }
    q.done = q.i
    if (q.i < q.todo) return false
    q.phase = 'release'
    return false
  }
  if (q.phase === 'wipe') {
    let c = q.c
    if (q.columns === undefined) {
      q.columns = []
      for (let z = box.z1; z <= box.z2; z++) for (let x = box.x1; x <= box.x2; x++) q.columns.push({ x: x, z: z })
      q.todo = q.columns.length
      q.i = 0
      q.air = consortiumHqParseState(level, 'minecraft:air')
    }
    let end = Math.min(q.todo, q.i + Math.floor(q.scanBudget / (c.clearTop + 3)))
    for (; q.i < end; q.i++) {
      let col = q.columns[q.i]
      for (let y = c.Y + 1; y <= box.y2; y++) {
        let pos = BlockPos.containing(col.x, y, col.z)
        if (!level.getBlockState(pos).isAir()) consortiumHqPlace(q, pos, q.air, CONSORTIUM_HQ_FLAG_CLIENTS)
      }
      consortiumHqPlace(q, BlockPos.containing(col.x, c.Y, col.z), c.ground, CONSORTIUM_HQ_FLAG_CLIENTS)
      for (let y = box.y1; y < c.Y; y++) consortiumHqPlace(q, BlockPos.containing(col.x, y, col.z), c.fill, CONSORTIUM_HQ_FLAG_CLIENTS)
    }
    q.done = q.i
    if (q.i < q.todo) return false
    q.phase = 'release'
    return false
  }
  // release: the ticket, the record, the box, the marks and the traps go; the world is saved.
  consortiumHqForce(level, box, false)
  server.persistentData.remove(CONSORTIUM_HQ_ROOT)
  server.persistentData.remove(CONSORTIUM_HQ_TRAPS_ROOT)
  server.runCommandSilent('save-all')
  let ticks = server.tickCount - q.startTick
  consortiumHqNotify(server, q.by, 'cleared: ' + consortiumFmt(q.placements) + ' blocks restored in ' + ticks + ' ticks, worst tick ' + q.worst + ' ms (' + consortiumHqWorstText(q) + ')' + (q.wipe ? ' (wipe fallback)' : '') + consortiumHqOutsideText(q) + '; the record, the box and the marks are dropped.', q.wipe || q.outside > 0)
  return true
}

// ---- the tick step and the lazy interrupted check ------------------------------------------------------------

function consortiumHqStep(server) {
  let q = consortiumHqQueue
  let start = Date.now()
  let finished = false
  try {
    if (q.kind === 'clear') {
      finished = consortiumHqClearStepRun(q)
    } else if (q.phase === 'snapshot') {
      q.snapshotTicks++
      if (consortiumHqSnapshotStep(q)) { q.phase = 'ground'; q.i = 0; q.columns = null }
    } else if (q.phase === 'ground') {
      if (consortiumHqGroundStep(q)) { q.phase = 'clear'; q.i = 0; q.todo = 0 }
    } else if (q.phase === 'clear') {
      if (consortiumHqClearStep(q)) { q.phase = 'layers'; q.i = 0; q.todo = 0 }
    } else if (q.phase === 'layers') {
      if (consortiumHqLayersStep(q)) { q.phase = 'finish'; q.i = 0 }
    } else if (q.phase === 'finish') {
      finished = consortiumHqFinishStep(q)
    }
  } catch (err) {
    console.error('[Consortium] HQ ' + q.kind + ' failed in phase ' + q.phase + ': ' + err)
    consortiumHqNotify(server, q.by, q.kind + ' aborted in phase ' + q.phase + ' (' + err + '): the force-load ticket is released; run consortium hq clear to restore the snapshot' + (q.kind === 'clear' ? ' again' : '') + '.', true)
    consortiumHqForce(q.level, q.box, false)
    let root = consortiumHqRoot(server, false)
    if (root !== null) root.putBoolean('forceloaded', false)
    consortiumHqQueue = null
    return
  }
  let ms = Date.now() - start
  q.ticks++
  if (ms > q.worst) q.worst = ms
  let phaseKey = q.kind === 'clear' ? q.phase : (q.phase === 'finish' && q.sub ? 'finish/' + q.sub : q.phase)
  if (q.phaseWorst[phaseKey] === undefined || ms > q.phaseWorst[phaseKey]) q.phaseWorst[phaseKey] = ms
  if (ms > CONSORTIUM_HQ_SLOW_MS) {
    q.budget = Math.max(CONSORTIUM_HQ_BUDGET_FLOOR, Math.floor(q.budget / 2))
    q.scanBudget = Math.max(CONSORTIUM_HQ_BUDGET_FLOOR * 10, Math.floor(q.scanBudget / 2))
    q.quiet = 0
  } else if (++q.quiet >= CONSORTIUM_HQ_QUIET_STEPS) {
    q.quiet = 0
    q.budget = Math.min(CONSORTIUM_HQ_PER_TICK, q.budget * 2)
    q.scanBudget = Math.min(CONSORTIUM_HQ_SCAN_PER_TICK, q.scanBudget * 2)
  }
  if (finished) consortiumHqQueue = null
}

// A build or clear interrupted by /reload, a crash or a stop left its force-load ticket: release it and warn.
function consortiumHqLazyCheck(server) {
  let root = consortiumHqRoot(server, false)
  if (root === null || !root.getBoolean('forceloaded')) return
  let box = consortiumHqBoxOf(root)
  if (box !== null) consortiumHqForce(consortiumHqLevelOf(server, root.getString('dim')), box, false)
  root.putBoolean('forceloaded', false)
  let text = root.getBoolean('built') ? 'clear interrupted: run hq clear again' : 'build interrupted: run hq clear, then hq build'
  consortiumHqNotify(server, '', text + ' (the force-load ticket is released).', true)
}

ServerEvents.tick((event) => {
  if (consortiumHqQueue === null) {
    if (!consortiumHqChecked) {
      consortiumHqChecked = true
      try { consortiumHqLazyCheck(event.server) } catch (err) { console.error('[Consortium] HQ interrupted-run check failed: ' + err) }
    }
    return
  }
  consortiumHqStep(event.server)
})

// ---- status, spawnpoint, forget ---------------------------------------------------------------------------

function consortiumHqMarkText(root, name) {
  let marks = root.getCompound('marks')
  if (!marks.contains(name)) return null
  let m = marks.getCompound(name)
  return m.getInt('x') + ' ' + m.getInt('y') + ' ' + m.getInt('z')
}

function consortiumHqMark(root, name) {
  let marks = root.getCompound('marks')
  if (!marks.contains(name)) return null
  let m = marks.getCompound(name)
  return BlockPos.containing(m.getInt('x'), m.getInt('y'), m.getInt('z'))
}

// The lines of /consortium hq status (strings; the command colours them).
function consortiumHqStatus(server) {
  let lines = []
  let root = consortiumHqRoot(server, false)
  let q = consortiumHqQueue
  if (root === null || !root.contains('box')) {
    lines.push('HQ: not built. /consortium hq build <x> <y> <z> <south|west|north|east> [<layout>] (y = the floor block level, x z = the spawn plinth centre).')
    return lines
  }
  if (q !== null) {
    let pct = q.todo > 0 ? Math.floor(100 * q.done / q.todo) : 0
    if (q.kind === 'build' && q.phase === 'snapshot') lines.push('HQ: snapshot (pass 0) ' + pct + ' %, ' + q.snapshotTicks + ' ticks so far, worst tick ' + q.worst + ' ms.')
    else lines.push('HQ: ' + (q.kind === 'build' ? 'building' : 'clearing') + ', phase ' + q.phase + (q.sub ? '/' + q.sub : '') + ' ' + pct + ' %, ' + consortiumFmt(q.placements) + ' placements, worst tick ' + q.worst + ' ms, budget ' + q.budget + ' per tick.')
  } else if (root.getBoolean('built')) {
    lines.push('HQ: built (record ' + (root.contains('record') ? 'present' : 'forgotten') + ').')
  } else if (root.contains('record')) {
    lines.push('HQ: interrupted, record present: run consortium hq clear.')
  } else {
    lines.push('HQ: interrupted, no record: nothing was written, run consortium hq clear to drop the box.')
  }
  let a = root.getCompound('anchor')
  let box = consortiumHqBoxOf(root)
  lines.push('Layout ' + root.getString('layout') + ', anchor ' + a.getInt('x') + ' ' + a.getInt('y') + ' ' + a.getInt('z') + ' facing ' + root.getString('facing') + ' in ' + root.getString('dim') + ', box ' + box.x1 + ' ' + box.y1 + ' ' + box.z1 + ' to ' + box.x2 + ' ' + box.y2 + ' ' + box.z2 + ' (' + (box.x2 - box.x1 + 1) + ' x ' + (box.y2 - box.y1 + 1) + ' x ' + (box.z2 - box.z1 + 1) + ')' + (root.getBoolean('forceloaded') ? ', force-loaded' : '') + (root.contains('by') ? ', by ' + root.getString('by') : '') + '.')
  let parts = []
  for (let name of ['spawn', 'arena', 'terminal', 'shop', 'waystone']) {
    let t = consortiumHqMarkText(root, name)
    if (t !== null) parts.push(name + ' ' + t)
  }
  lines.push('marks: ' + parts.join(', '))
  if (server.persistentData.contains(CONSORTIUM_HQ_TRAPS_ROOT)) {
    let tr = server.persistentData.getCompound(CONSORTIUM_HQ_TRAPS_ROOT)
    lines.push('traps: ' + tr.getList('traps', 10).size() + ' group(s), mode ' + tr.getString('mode') + (typeof consortiumTrapsLive === 'function' ? (consortiumTrapsLive(server) ? ', live now' : ', idle') : '') + ' (/consortium hq traps).')
  }
  let ring = root.getCompound('arena')
  let arenaMark = consortiumHqMark(root, 'arena')
  let claimAdvice = consortiumHqClaimOf(box)
  if (typeof consortiumArena === 'function' && arenaMark !== null) {
    let arena = consortiumArena(server)
    if (arena === null) {
      lines.push('arena: unset (run consortium hq spawnpoint arena <member> once the staff party exists).')
    } else {
      let issues = []
      if (arena.dim !== String(root.getString('dim')) || arena.x !== arenaMark.getX() || arena.y !== arenaMark.getY() || arena.z !== arenaMark.getZ()) issues.push('arena centre ' + arena.x + ' ' + arena.y + ' ' + arena.z + ' is not the arena mark ' + consortiumHqPosText(arenaMark) + ': run consortium hq spawnpoint arena <member>')
      if (arena.ringMin !== ring.getInt('ringMin') || arena.ringMax !== ring.getInt('ringMax') || arena.pit !== ring.getInt('pit')) issues.push('arena ring ' + arena.ringMin + '..' + arena.ringMax + ' pit ' + arena.pit + ' is not the layout ring ' + ring.getInt('ringMin') + '..' + ring.getInt('ringMax') + ' pit ' + ring.getInt('pit') + ': run consortium event arena ring ' + ring.getInt('ringMin') + ' ' + ring.getInt('ringMax') + ' ' + ring.getInt('pit'))
      if (typeof consortiumClaimManager === 'function') {
        let mgr = consortiumClaimManager()
        let level = consortiumHqLevelOf(server, root.getString('dim'))
        let claim = mgr === null ? null : consortiumClaimAt(mgr, level, arenaMark)
        if (claim === null) issues.push('the arena mark is unclaimed: run ftbchunks admin claim_as <staff party> ' + claimAdvice.radius + ' ' + claimAdvice.x + ' ' + claimAdvice.z + ' ' + root.getString('dim'))
        else if (consortiumClaimTeamId(claim) !== arena.team) issues.push('the claim at the arena mark belongs to ' + consortiumClaimTeamId(claim) + ', not to the arena team ' + arena.team)
      }
      if (issues.length === 0) lines.push('arena: OK (centre, ring ' + arena.ringMin + '..' + arena.ringMax + ', pit ' + arena.pit + ', team ' + arena.team + ').')
      else for (let i = 0; i < issues.length; i++) lines.push('arena: ' + issues[i])
    }
  }
  lines.push('After the build, in this order: /ftbteams party create staff (in game), ftbchunks admin extra_claim_chunks <member> add ' + claimAdvice.count + ', ftbchunks admin claim_as staff ' + claimAdvice.radius + ' ' + claimAdvice.x + ' ' + claimAdvice.z + ' ' + root.getString('dim') + ' (' + claimAdvice.count + ' chunks: the box plus a ' + CONSORTIUM_HQ_STAFF_CLAIM_BUFFER + '-chunk buffer), consortium hq spawnpoint arena <member>, ftbteams settings_for staff ftbchunks:block_interact_mode public.')
  return lines
}

// /consortium hq spawnpoint [arena [<player>]]: the world spawn on the plinth (open sky, the heightmap fudge
// lands newcomers on it) and, with `arena`, the events arena record from the layout's ring and pit.
function consortiumHqSpawnpoint(server, withArena, member) {
  let root = consortiumHqRoot(server, false)
  if (root === null || !root.contains('marks')) return { ok: false, reason: 'No HQ is recorded: run consortium hq build first.' }
  let spawn = consortiumHqMark(root, 'spawn')
  if (spawn === null) return { ok: false, reason: 'The recorded HQ has no spawn mark.' }
  let lines = []
  server.runCommandSilent('execute in ' + root.getString('dim') + ' run setworldspawn ' + consortiumHqPosText(spawn))
  server.runCommandSilent('gamerule spawnRadius 0')
  lines.push('World spawn set to ' + consortiumHqPosText(spawn) + ' (the plinth), spawnRadius 0.')
  if (!withArena) return { ok: true, lines: lines }
  if (typeof consortiumEvents !== 'function' || typeof consortiumArena !== 'function') return { ok: false, reason: 'The events engine is not loaded: no arena record can be written.' }
  let arenaMark = consortiumHqMark(root, 'arena')
  if (arenaMark === null) return { ok: false, reason: 'The recorded HQ has no arena mark.' }
  let team = consortiumTeamOfId(member.id)
  if (team === null) return { ok: false, reason: 'FTB Teams has no team for ' + member.name + '.' }
  if (!team.isPartyTeam()) return { ok: false, reason: 'The team of ' + member.name + ' is not a party: create the staff party first (/ftbteams party create staff, then invite the staff), then run this again.' }
  let ring = root.getCompound('arena')
  let a = NBT.compoundTag()
  a.putString('dim', String(root.getString('dim')))
  a.putInt('x', arenaMark.getX()); a.putInt('y', arenaMark.getY()); a.putInt('z', arenaMark.getZ())
  a.putString('team', String(team.getId()).toLowerCase())
  a.putInt('radius', 3)
  a.putInt('ringMin', ring.getInt('ringMin')); a.putInt('ringMax', ring.getInt('ringMax')); a.putInt('pit', ring.getInt('pit'))
  consortiumEvents(server).put('arena', a)
  let arena = consortiumArena(server)
  consortiumHqLog('arena recorded at ' + consortiumHqPosText(arenaMark) + ' for the party of ' + member.name + ' (' + arena.team + '), ' + consortiumArenaRingText(arena))
  lines.push('Arena: ' + arena.dim + ' ' + arena.x + ' ' + arena.y + ' ' + arena.z + ', team ' + arena.team + ' (the party of ' + member.name + '), radius ' + arena.radius + ' chunk(s), ' + consortiumArenaRingText(arena) + '.')
  return { ok: true, lines: lines }
}

// /consortium hq forget: drops the record, the box and the marks without touching a block.
function consortiumHqForget(server, by) {
  if (consortiumHqQueue !== null) return { ok: false, reason: 'An HQ ' + consortiumHqBusyText() + ' runs: wait for its finish line.' }
  let root = consortiumHqRoot(server, false)
  if (root === null) return { ok: false, reason: 'No HQ is recorded.' }
  let box = consortiumHqBoxOf(root)
  if (box !== null && root.getBoolean('forceloaded')) consortiumHqForce(consortiumHqLevelOf(server, root.getString('dim')), box, false)
  server.persistentData.remove(CONSORTIUM_HQ_ROOT)
  server.runCommandSilent('save-all')
  consortiumHqLog(by + ' hq forget: the record, the box and the marks are dropped; hq clear is no longer possible')
  return { ok: true, text: 'HQ record forgotten: the blocks stay, the snapshot is gone, so hq clear is no longer possible (the save file shrinks at the next save).' }
}

console.info('[Consortium] HQ generator loaded (' + CONSORTIUM_HQ_DATA + '<layout>.json, /consortium hq build|status|clear|spawnpoint|forget)')
